<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tolak</name>
   <tag></tag>
   <elementGuidId>03a8c67e-ba10-48d2-8812-f116614d2771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='blockNotif'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77f17a47-01cc-4c79-b5ba-a7937792b37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moe-chrome-style-notification-btn moe-btn-close moe-block-class</value>
      <webElementGuid>0e57124a-a62e-45bb-a774-1fff781bfe5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>blockNotif</value>
      <webElementGuid>1ea7acbd-d50e-45a1-a758-68635597e5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tolak</value>
      <webElementGuid>72668707-1e5b-4f79-80f4-cbabd0d3d3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;moe-main-class&quot;]/div[@class=&quot;moe-chrome-style-notification moe-chrome-style-notification-safari&quot;]/div[@class=&quot;moe-safari-notification-inner-wrapper&quot;]/div[3]/div[@class=&quot;moe-button-wrapper&quot;]/button[@id=&quot;blockNotif&quot;]</value>
      <webElementGuid>0909e81b-a5d5-4a42-89d6-16c91880d686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='blockNotif'])[2]</value>
      <webElementGuid>9d0f37e7-bc3f-4576-9fc4-25ee71e97837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website Cermati.com ingin mengirimkan update dan penawaran menarik!'])[2]/following::button[1]</value>
      <webElementGuid>21df0893-8537-4343-822e-2f927ec71541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Izinkan'])[1]/following::button[1]</value>
      <webElementGuid>8f411d91-7030-4de1-98c3-069bf28d43f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Izinkan'])[2]/preceding::button[1]</value>
      <webElementGuid>d74fc658-f5b1-4b62-a5f8-85ed1a997cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div/button</value>
      <webElementGuid>618ba46b-9064-4312-af2b-35e389cfdb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'blockNotif' and (text() = 'Tolak' or . = 'Tolak')]</value>
      <webElementGuid>589a4444-5b4e-4bb1-a624-f42eb4fee211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
