<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan 6 digit PIN baru Anda_newPin_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>1bc011fc-47c5-47a4-bd9e-8c7ae2f6a7a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pin-input-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pin-input-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b33ad6ab-e4be-4edc-8ade-e011534b848b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bb4fc86b-3344-44b4-a32e-077191457c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp__input_30CvO false</value>
      <webElementGuid>728beeca-b380-4e45-ae32-ae0a18804937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pin-input-5</value>
      <webElementGuid>f9707134-dad6-4de4-84cf-34999c8f4011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newPin</value>
      <webElementGuid>b7392bd8-824c-4cf4-bb07-c1d3420fb3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9.]+</value>
      <webElementGuid>9da5faa7-0cd8-4520-9e5b-c820008379a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>059fed8e-e0f8-4557-a4d0-65316dd15ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin-input-5&quot;)</value>
      <webElementGuid>4dbd59f3-999e-4e60-a4b4-30d19488bfd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pin-input-5']</value>
      <webElementGuid>412a904c-ecd5-4da4-abfe-ad79eff6a667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div/div/div/div[6]/input</value>
      <webElementGuid>f19b2afe-d2c9-47ca-9350-c87019ce8649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>2222c95c-8f32-46b0-aa4a-7136a0bde24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pin-input-5' and @name = 'newPin' and @type = 'tel']</value>
      <webElementGuid>c800a0e2-0789-4249-8345-e79aed0e32de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
