<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ke_otp_1</name>
   <tag></tag>
   <elementGuidId>f13d3c35-28f5-463c-9118-81b440aba034</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pin-input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pin-input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a78585e-6252-48bb-8043-00bca24c1ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a392034f-9110-4cdb-972e-b5f669443633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp__input_30CvO false</value>
      <webElementGuid>2c982f39-9974-4823-a2d2-87badd238890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pin-input-1</value>
      <webElementGuid>a1dcc73f-42d5-4f1b-95e7-cf6c4c0b3878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp</value>
      <webElementGuid>0d703dd8-e335-4615-a4f4-bdd505f102e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9.]+</value>
      <webElementGuid>838db296-c4e3-4d03-9edb-ffae3e6d3113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4c802f0a-e136-4f27-bacc-00d7a16f3d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin-input-1&quot;)</value>
      <webElementGuid>225c3831-61c8-4662-a45c-f7877f862eea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pin-input-1']</value>
      <webElementGuid>afad50db-d793-469e-a99f-27dca753ca27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>6167de55-48c8-425f-84a8-8fbccad5a6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7c793fbf-8d2f-4070-bc66-f193da238479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pin-input-1' and @name = 'otp' and @type = 'tel']</value>
      <webElementGuid>aa15651a-5fbd-4160-b590-b9354f61d1f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
